Scenario_Stage = CBSTestPlan_10% Volume
IB_AddThread = 4
IB_AddLoop = 5
IB_AddPacing = 10
IB_AddRampUp = 12
IB_ChangeThread = 2
IB_ChangeLoop = 15
IB_ChangePacing = 10
IB_ChangeRampUp = 18
IB_RemoveThread = 3
IB_RemoveLoop = 12
IB_RemovePacing = 10
IB_RemoveRampUp = 10
IB_CreateThread = 1
IB_CreateLoop = 12
IB_CreatePacing = 10
IB_CreateRampUp = 12
IB_UpdateThread = 2
IB_UpdateLoop = 10
IB_UpdatePacing = 10
IB_UpdateRampUp = 24
IB_DeleteThread = 2
IB_DeleteLoop = 8
IB_DeletePacing = 10
IB_DeleteRampUp = 24
OperatingSystem = Windows
InfluxDBIP = localhost
InfluxDBPort = 8086
JmeterBinFolderPath = C:\Users\nftuser\Documents\apache-jmeter-5.5\bin
summariser.name = Summary
summariser.interval = TRUE
summariser.log = TRUE
summariser.out = TRUE
summariser.ignore_transaction_controller_sample_result = TRUE
jmeter.save.saveservice.output_format = jtl
httpclient.socket.http.cps = 0
httpclient.socket.https.cps = 0
