Scenario_Stage = IBTestPlan_Final_30% Volume
CreateThread = 3
CreateLoop = 25
CreatePacing = 10
CreateRampUp = 36
Create_UserThread = 9
Create_UserLoop = 4
Create_UserPacing = 10
Create_UserRampUp = 75
UpdateThread = 6
UpdateLoop = 15
UpdatePacing = 10
UpdateRampUp = 72
Update_UserThread = 12
Update_UserLoop = 9
Update_UserPacing = 10
Update_UserRampUp = 90
DeleteThread = 6
DeleteLoop = 9
DeletePacing = 10
DeleteRampUp = 72
Delete_UserThread = 3
Delete_UserLoop = 32
Delete_UserPacing = 10
Delete_UserRampUp = 36
OperatingSystem = Windows
InfluxDBIP = localhost
InfluxDBPort = 8086
JmeterBinFolderPath = C:\Users\nftuser\Documents\apache-jmeter-5.5\bin
summariser.name = Summary
summariser.interval = TRUE
summariser.log = TRUE
summariser.out = TRUE
summariser.ignore_transaction_controller_sample_result = TRUE
jmeter.save.saveservice.output_format = jtl
httpclient.socket.http.cps = 0
httpclient.socket.https.cps = 0
