Scenario_Stage = petclinictestplan_30% Volume
Home_PageThread = 3
Home_PageLoop = 25
Home_PagePacing = 10
Home_PageRampUp = 36
Search _For_VetsThread = 6
Search _For_VetsLoop = 15
Search _For_VetsPacing = 10
Search _For_VetsRampUp = 72
OwnersThread = 6
OwnersLoop = 9
OwnersPacing = 10
OwnersRampUp = 72
petclinictestplan_Duration = 3600
OperatingSystem = Windows
InfluxDBIP = localhost
InfluxDBPort = 8086
JmeterBinFolderPath = C:\Users\nftuser\Documents\apache-jmeter-5.5\bin
summariser.name = Summary
summariser.interval = TRUE
summariser.log = TRUE
summariser.out = TRUE
summariser.ignore_transaction_controller_sample_result = TRUE
jmeter.save.saveservice.output_format = jtl
httpclient.socket.http.cps = 0
httpclient.socket.https.cps = 0
