Scenario_Stage = petclinictestplan_60% Volume
Home_PageThread = 6
Home_PageLoop = 25
Home_PagePacing = 10
Home_PageRampUp = 72
Search_For_VetsThread = 12
Search_For_VetsLoop = 15
Search_For_VetsPacing = 10
Search_For_VetsRampUp = 144
OwnersThread = 12
OwnersLoop = 9
OwnersPacing = 10
OwnersRampUp = 144
petclinictestplan_Duration = 1200
OperatingSystem = Windows
InfluxDBIP = localhost
InfluxDBPort = 8086
JmeterBinFolderPath = C:\Users\nftuser\Documents\apache-jmeter-5.5\bin
summariser.name = Summary
summariser.interval = TRUE
summariser.log = TRUE
summariser.out = TRUE
summariser.ignore_transaction_controller_sample_result = TRUE
jmeter.save.saveservice.output_format = jtl
httpclient.socket.http.cps = 0
httpclient.socket.https.cps = 0
